services:
  app:
    build: ./app
    ports:
      - "5001:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - GEMMA_API_URL=http://gemma:8080  # Direct connection to gemma
    depends_on:
      - chroma
      - gemma
    networks:
      - moroccan-gemma-network

  gemma:
    build: ./gemma
    ports:
      - "8080:8080"
    volumes:
      - ./gemma:/gemma
      - ./data:/data
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - moroccan-gemma-network

  chroma:
    build: ./chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma/data:/chroma/data
      - ./data:/data
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSIST_DIRECTORY=/chroma/data
    networks:
      - moroccan-gemma-network

networks:
  moroccan-gemma-network:
    driver: bridge